# -*- coding: utf-8 -*-
"""doctr-ocr-notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c5dmVW-nOFsBhcQGFU8gxVp9QLW1SU3o
"""

!pip install -e git+https://github.com/mindee/doctr.git#egg=python-doctr[torch]

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import os

#Let's pick desired backend
#os.environ['USE_TF'] = '1'
os.environ['USE_TORCH'] = '1'

import matplotlib.pyplot as plt

from doctr.io import DocumentFile
from doctr.models import ocr_predictor

model = ocr_predictor(pretrained=True)

document = DocumentFile.from_images("/content/SamsClub.jpeg")

result = model(document)

result.show(document)

json_response = result.export()

json_response