# -*- coding: utf-8 -*-
"""doctr-ocr-notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c5dmVW-nOFsBhcQGFU8gxVp9QLW1SU3o
"""

#pip install -e git+https://github.com/mindee/doctr.git#egg=python-doctr[torch]

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import os

#Let's pick desired backend
#os.environ['USE_TF'] = '1'
os.environ['USE_TORCH'] = '1'

import json
import matplotlib.pyplot as plt

from doctr.io import DocumentFile
from doctr.models import ocr_predictor

model = ocr_predictor(pretrained=True)

#Update the Input Image Path
document = DocumentFile.from_images("C:\\Users\\navee\\Documents\\Soloprenuer\\GROP\\GROP\\Python\\Images\\Bucee.jpeg")

result = model(document)

#result.show(document)

json_response = result.export()

#Save the Json Output to a file
json_object = json.dumps(json_response, indent=4)
with open("C:\\Users\\navee\\Documents\\Soloprenuer\\GROP\\GROP\\Python\\Images\\sample4.json", "w") as outfile:
    outfile.write(json_object)